### PR TITLE
Enhancement: Basic UI improvements for the editor

### PR DESCRIPTION
**Pull request by divyanshudhruv**
## Description

This pull request includes improvements to the UI, such as, updating button styles, adjusting heights, colors, and borders and code editor default background color. These changes aim to enhance the overall look and feel of the interface for a better user experience. It basically separates the editor into 2 main areas- File viewer (left), text editor (right)

### Changes: 
1. Add custom height, letter spacing in the status bar.
2. Updated the title text from `XediX` to `XediX - Text Editor`
3. Updated the style of Buttons.
4. UI of `Notebook` (text area) mainly width, height, padding.
5. Reduced the size of `Open a File first` text.
6. Reduced the code editor left margin (for line numbers).
7. Overall color improvement, etc.

### Screenshots:

> Old: 

> New: 

## Type of change
Check options that apply:

- [x] UI Update ("update the overall UI of the editor)

## How Has This Been Tested?
Operating System: Windows 11 (64-bit)
Code Editor: VSCode

- [ ] Tried it with pyinstaller. **(recommended)**
- [x] Just running the code.

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Added new dependencies to requiremnts.txt

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
@mostypc123 Please review the PR. I'm happy to make further improvements if needed as per your suggestion.

**Review by mostypc123 — CHANGES_REQUESTED** [review]
very great, but some stuff **like the pywinstyles theme which is being saved in wintheme.xcfg or the requirements.py i added _(sorry for review after adding changes, i didn't see it)_**

also it might be great if the **header color will be saved in a xedix config file.** it's also a weird color on the header that makes it look like an inactive window, because you know - when a window is _inactive_ the header is gray, and normally it is the color you set in Settings > Customization.

but overall it's very good of a change, will merge after that will be fixed.

**Comment by divyanshudhruv** [comment]
Got it,but can you specify the colors for the header both active and inactive, I'll fix that ASAP.

**Comment by mostypc123** [comment]
one last thing to fix, new file button is looking much better, but maybe other buttons should have that style. it is okay like this too, but that will be a big plus.

**Comment by mostypc123** [comment]
dont care about the requirements.py that was in an another branch, i just thougt i merged it already

**Comment by divyanshudhruv** [comment]
> one last thing to fix, new file button is looking much better, but maybe other buttons should have that style. it is okay like this too, but that will be a big plus.

Yep, I will try to change all the buttons too if possible, in this PR

**Comment by divyanshudhruv** [comment]
## Updates

- Added `xedix.xcfg` for user-based UI customizations.
- Enabled dynamic header color changes based on window state.
- Added `Customize` under `Tools` to open `xedix.xcfg` with the `OnCustomize` method for editing and theme application.

**Review by mostypc123 — APPROVED** [review]
that looks good, will probably merge soon

**Comment by divyanshudhruv** [comment]
🙂👍

**Comment by divyanshudhruv** [comment]
> that looks good, will probably merge soon

Ah, when will you merge it :)

**Comment by mostypc123** [comment]
im on github mobile right now so tommorow in the evening

**Comment by divyanshudhruv** [comment]
:)

**Pull request merged**
